/**
 * ATK Inventory - Frontend V2
 * UI, navigation, scanner, requests, approvals, PO, reports and Excel import/export.
 * Backend endpoint: /api/app
 */

"use strict";
const API="/api/app";
const S={token:localStorage.getItem("atk_token")||"",user:null,page:"dashboard",products:[],categories:[],suppliers:[],receiptItems:[],requestItems:[],poItems:[],scanner:null,importRows:[]};
const $=id=>document.getElementById(id); const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;", "'":"&#39;"}[m])); const num=v=>Number.isFinite(Number(v))?Number(v):0; const money=v=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(num(v)); const nfmt=v=>new Intl.NumberFormat("id-ID").format(num(v));
const today=()=>{const d=new Date(),x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};

function busy(x){$("load").classList.toggle("hidden",!x)} function toast(msg,type="info"){const d=document.createElement("div");d.textContent=msg;Object.assign(d.style,{position:"fixed",right:"16px",bottom:"16px",zIndex:300,padding:"11px 13px",borderRadius:"10px",fontSize:"12px",fontWeight:"700",background:type==="error"?"#fee2e2":type==="success"?"#dcfce7":"#e0f2fe",color:type==="error"?"#991b1b":type==="success"?"#166534":"#075985",boxShadow:"0 8px 25px rgba(0,0,0,.15)"});document.body.appendChild(d);setTimeout(()=>d.remove(),2600)}

function badge(v){let c="b-m";if(["AMAN","DISETUJUI_PENUH","COMPLETED"].includes(v))c="b-ok";else if(["MENUNGGU","PERLU_ORDER","DRAFT","ORDERED","PARTIAL"].includes(v))c="b-w";else if(["HABIS","PERLU_SEGERA_ORDER","DITOLAK","CANCELLED"].includes(v))c="b-e";else if(["DISETUJUI_SEBAGIAN","IN","OUT"].includes(v))c="b-i";return `<span class="badge ${c}">${esc(String(v||"").replaceAll("_"," "))}</span>`}

function modal(body,footer=""){$("modal").innerHTML=`<div class="modal-bg"><div class="modal">${body}${footer?`<div class="mf">${footer}</div>`:""}</div></div>`} function closeModal(){stopScanner();$("modal").innerHTML=""}

async function api(action,p={}){const x={action,...p};if(S.token)x.sessionToken=S.token;busy(true);try{const r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(x)});const text=await r.text();let o;try{o=JSON.parse(text)}catch(_){throw new Error("Respons server tidak valid.")}if(!r.ok||!o.ok){if(/Session/i.test(o.error||""))logout(false);throw new Error(o.error||`HTTP ${r.status}`)}return o}catch(e){throw new Error(e?.message||"Koneksi ke server gagal.")}finally{busy(false)}}

async function login(e){e.preventDefault();$("loginErr").classList.add("hidden");try{const o=await api("login",{username:$("liUser").value.trim(),password:$("liPass").value});S.token=o.sessionToken;S.user=o.user;localStorage.setItem("atk_token",S.token);await start()}catch(x){$("loginErr").textContent=x.message;$("loginErr").classList.remove("hidden")}}

function logout(send=true){if(send&&S.token)api("logout").catch(()=>{});S.token="";S.user=null;localStorage.removeItem("atk_token");$("appView").classList.add("hidden");$("loginView").classList.remove("hidden");closeModal()}

async function start(){try{if(!S.user)S.user=(await api("me")).user;$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");$("uName").textContent=S.user.name;$("uRole").textContent=S.user.role+" • "+(S.user.department||"");buildNav();await go("dashboard")}catch(e){logout(false)}}

function buildNav(){const A=S.user.role==="ADMIN";const groups=A?[["UTAMA",[["dashboard","Dashboard","▦"]]],["MASTER",[["products","Master Barang","▤"],["categories","Kategori","◫"],["suppliers","Supplier","⌂"],["users","User","♙"]]],["PERSEDIAAN",[["receipts","Barang Masuk","↓"],["adjust","Adjustment / Opname","±"],["movements","Histori Mutasi","↕"]]],["PENGADAAN",[["reorder","Rekomendasi Order","⚑"],["pos","Purchase Order","▣"]]],["PENGAJUAN",[["requests","Approval Pengajuan","✓"]]],["LAPORAN",[["report","Laporan Stok","▥"],["import","Import Excel","⇪"]]]]:[["UTAMA",[["dashboard","Dashboard","▦"],["search","Cari Barang","⌕"],["myrequests","Pengajuan Saya","✓"]]]];$("nav").innerHTML=groups.map(g=>`<div class="ng">${g[0]}</div>${g[1].map(x=>`<button class="navbtn ${S.page===x[0]?"active":""}" data-go="${x[0]}"><span style="width:18px;text-align:center">${x[2]}</span>${x[1]}</button>`).join("")}`).join("");$("nav").querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>{go(b.dataset.go);$("side").classList.remove("open")})}

async function go(page){S.page=page;buildNav();const f={dashboard,products,categories,suppliers,users,receipts,adjust,movements,reorder,pos,requests,report,import:importPage,search,myrequests}[page];if(f)await f()}

function title(a,b){$("tt").textContent=a;$("ts").textContent=b||""} function jump(p){go(p)}

async function masters(){const [c,s,p]=await Promise.all([api("listCategories"),api("listSuppliers"),api("listProducts")]);S.categories=c.items||[];S.suppliers=s.items||[];S.products=p.items||[]}

function stat(label,value,sub){return `<div class="card stat"><small>${label}</small><strong>${value}</strong><small>${sub}</small></div>`}

async function dashboard(){title("Dashboard","Ringkasan persediaan ATK");const o=await api("dashboard"),c=o.cards;let h=`<div class="head"><div><h2>Dashboard</h2><p>Selamat datang, ${esc(S.user.name)}</p></div></div><div class="grid g4">${stat("Total Jenis Barang",nfmt(c.totalTypes),"item aktif")}${stat("Total Stok",nfmt(c.totalStock),"unit")}${stat("Stok Menipis",nfmt(c.lowStock),"minimum / di bawah")}${stat("Pengajuan Menunggu",nfmt(c.pendingRequests),"perlu diproses")}</div>`;if(S.user.role==="ADMIN"){h+=stat("Nilai Persediaan",money(c.totalValue),"stok × harga");const r=await api("reorderRecommendations");h+=`<div class="card" style="margin-top:12px"><b>Barang yang Perlu Order</b><div style="margin-top:10px">${reorderTable(r.items)}</div></div>`}else h+=`<div class="grid g2" style="margin-top:12px"><div class="card"><h3 style="margin-top:0">Cari Barang</h3><p class="muted">Cari dengan nama/SKU atau scan barcode.</p><button class="btn primary" onclick="jump('search')">Buka Pencarian</button></div><div class="card"><h3 style="margin-top:0">Pengajuan</h3><p class="muted">Buat dan pantau pengajuan.</p><button class="btn primary" onclick="jump('myrequests')">Lihat Pengajuan</button></div></div>`;$("content").innerHTML=h}

function table(headers,rows){return rows.length?`<div class="tw"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.map(x=>`<tr>${x}</tr>`).join("")}</tbody></table></div>`:`<div class="muted" style="padding:20px;text-align:center">Tidak ada data.</div>`}

function categoryName(id){return S.categories.find(x=>x.categoryId===id)?.categoryName||"-"} function supplierName(id){return S.suppliers.find(x=>x.supplierId===id)?.name||"-"}

async function products(){title("Master Barang","Data master ATK");await masters();$("content").innerHTML=`<div class="head"><div><h2>Master Barang</h2></div><button class="btn primary" id="addp">+ Barang</button></div><div class="card"><div class="toolbar"><div class="field"><label>Cari</label><input id="pq" class="inp" placeholder="SKU / barcode / nama"></div><div class="field"><label>Status</label><select id="ps" class="sel"><option value="">Semua</option><option value="active">Aktif</option><option value="inactive">Nonaktif</option><option value="low">Menipis</option><option value="out">Habis</option></select></div></div><div id="pt"></div></div>`;const draw=()=>{let a=[...S.products],q=$("pq").value.toLowerCase(),s=$("ps").value;a=a.filter(p=>!q||[p.sku,p.barcode,p.name].some(v=>String(v).toLowerCase().includes(q))).filter(p=>!s||(s==="active"?p.active:s==="inactive"?!p.active:s==="low"?["PERLU_ORDER","PERLU_SEGERA_ORDER"].includes(p.status):p.status==="HABIS"));$("pt").innerHTML=table(["SKU","Barcode","Nama","Kategori","Satuan","Min","Max","Stok","Harga","Supplier","Status","Aksi"],a.map(p=>`<td>${esc(p.sku)}</td><td>${esc(p.barcode)}</td><td><b>${esc(p.name)}</b></td><td>${esc(categoryName(p.categoryId))}</td><td>${esc(p.unit)}</td><td>${nfmt(p.minStock)}</td><td>${nfmt(p.maxStock)}</td><td><b>${nfmt(p.currentStock)}</b></td><td>${money(p.price)}</td><td>${esc(supplierName(p.supplierId))}</td><td>${badge(p.status)}</td><td><button class="btn sm" data-ep="${p.productId}">Edit</button> <button class="btn sm ${p.active?"danger":"success"}" data-tp="${p.productId}">${p.active?"Nonaktifkan":"Aktifkan"}</button></td>`))};$("pq").oninput=draw;$("ps").onchange=draw;$("addp").onclick=()=>productForm();draw()}

function productForm(p=null){modal(`<div class="mh"><b>${p?"Edit":"Tambah"} Barang</b><button class="btn sm" onclick="closeModal()">✕</button></div><div class="mb"><div class="fg">${field("psku","SKU",p?.sku||"")}${field("pbc","Barcode",p?.barcode||"")}${field("pname","Nama Barang",p?.name||"")}${select("pcat","Kategori",S.categories.map(x=>[x.categoryId,x.categoryName]),p?.categoryId||"")}${field("punit","Satuan",p?.unit||"PCS")}${field("pmin","Stok Minimal",p?.minStock??5,"number")}${field("pmax","Stok Maksimal",p?.maxStock??10,"number")}${field("pprice","Harga",p?.price??0,"number")}${select("psup","Supplier",S.suppliers.map(x=>[x.supplierId,x.name]),p?.supplierId||"")}${field("ploc","Lokasi",p?.location||"")}<div class="field"><label>Barcode Kamera</label><button class="btn info" type="button" onclick="scannerFor('product')">▣ Scan Barcode</button></div></div></div>`,`<button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="savep">Simpan</button>`);$("savep").onclick=async()=>{const item={sku:$("psku").value,barcode:$("pbc").value,name:$("pname").value,categoryId:$("pcat").value,unit:$("punit").value,minStock:num($("pmin").value),maxStock:num($("pmax").value),price:num($("pprice").value),supplierId:$("psup").value,location:$("ploc").value};try{await api(p?"updateProduct":"createProduct",p?{productId:p.productId,item}:{item});closeModal();toast("Barang tersimpan","success");products()}catch(e){toast(e.message,"error")}}}

function field(id,label,value="",type="text"){return `<div class="field"><label>${label}</label><input id="${id}" class="inp" type="${type}" value="${esc(value)}"></div>`}function select(id,label,opts,value=""){return `<div class="field"><label>${label}</label><select id="${id}" class="sel"><option value="">- Pilih -</option>${opts.map(x=>`<option value="${esc(x[0])}" ${x[0]===value?"selected":""}>${esc(x[1])}</option>`).join("")}</select></div>`}

async function categories(){title("Kategori","Master kategori");const o=await api("listCategories");$("content").innerHTML=`<div class="head"><div><h2>Kategori</h2></div><button class="btn primary" id="ac">+ Kategori</button></div><div class="card">${table(["ID","Nama","Status","Aksi"],o.items.map(c=>`<td>${esc(c.categoryId)}</td><td>${esc(c.categoryName)}</td><td>${badge(String(c.active).toUpperCase()==="TRUE"?"AMAN":"NONAKTIF")}</td><td><button class="btn sm" data-ec="${c.categoryId}">Edit</button></td>`))}</div>`;$("ac").onclick=()=>catForm();$("content").querySelectorAll("[data-ec]").forEach(b=>b.onclick=()=>catForm(o.items.find(x=>x.categoryId===b.dataset.ec)))}

function catForm(c=null){modal(`<div class="mh"><b>${c?"Edit":"Tambah"} Kategori</b><button class="btn sm" onclick="closeModal()">✕</button></div><div class="mb">${field("catname","Nama Kategori",c?.categoryName||"")}</div>`,`<button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="cats">Simpan</button>`);$("cats").onclick=async()=>{try{await api(c?"updateCategory":"createCategory",c?{categoryId:c.categoryId,categoryName:$("catname").value}:{categoryName:$("catname").value});closeModal();toast("Tersimpan","success");categories()}catch(e){toast(e.message,"error")}}}

async function suppliers(){title("Supplier","Master supplier");const o=await api("listSuppliers");$("content").innerHTML=`<div class="head"><div><h2>Supplier</h2></div><button class="btn primary" id="as">+ Supplier</button></div><div class="card">${table(["Kode","Nama","PIC","Telepon","Email","Alamat","Aksi"],o.items.map(s=>`<td>${esc(s.code)}</td><td>${esc(s.name)}</td><td>${esc(s.pic)}</td><td>${esc(s.phone)}</td><td>${esc(s.email)}</td><td>${esc(s.address)}</td><td><button class="btn sm" data-es="${s.supplierId}">Edit</button></td>`))}</div>`;$("as").onclick=()=>supplierForm();$("content").querySelectorAll("[data-es]").forEach(b=>b.onclick=()=>supplierForm(o.items.find(x=>x.supplierId===b.dataset.es)))}

function supplierForm(s=null){modal(`<div class="mh"><b>${s?"Edit":"Tambah"} Supplier</b><button class="btn sm" onclick="closeModal()">✕</button></div><div class="mb"><div class="fg">${field("sco","Kode",s?.code||"")}${field("sna","Nama",s?.name||"")}${field("spic","PIC",s?.pic||"")}${field("sph","Telepon",s?.phone||"")}${field("sem","Email",s?.email||"")}${field("sad","Alamat",s?.address||"")}</div></div>`,`<button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="sus">Simpan</button>`);$("sus").onclick=async()=>{const item={code:$("sco").value,name:$("sna").value,pic:$("spic").value,phone:$("sph").value,email:$("sem").value,address:$("sad").value,active:true};try{await api(s?"updateSupplier":"createSupplier",s?{supplierId:s.supplierId,item}:{item});closeModal();toast("Supplier tersimpan","success");suppliers()}catch(e){toast(e.message,"error")}}}

async function users(){title("User","Kelola Admin/Staff");const o=await api("listUsers");$("content").innerHTML=`<div class="head"><div><h2>User</h2></div><button class="btn primary" id="au">+ User</button></div><div class="card">${table(["Username","Nama","Email","Role","Departemen","Status","Aksi"],o.items.map(u=>`<td>${esc(u.username)}</td><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${badge(u.role)}</td><td>${esc(u.department)}</td><td>${badge(u.active?"AMAN":"NONAKTIF")}</td><td><button class="btn sm" data-eu="${u.userId}">Edit</button></td>`))}</div>`;$("au").onclick=()=>userForm();$("content").querySelectorAll("[data-eu]").forEach(b=>b.onclick=()=>userForm(o.items.find(x=>x.userId===b.dataset.eu)))}

function userForm(u=null){modal(`<div class="mh"><b>${u?"Edit":"Tambah"} User</b><button class="btn sm" onclick="closeModal()">✕</button></div><div class="mb"><div class="fg">${field("uun","Username",u?.username||"")}${field("una","Nama",u?.name||"")}${field("uem","Email",u?.email||"")}${select("urole","Role",[["STAFF","Staff"],["ADMIN","Admin"]],u?.role||"STAFF")}${field("udep","Departemen",u?.department||"")}${field("upw","Password baru","","password")}</div><div class="muted" style="font-size:10px;margin-top:8px">Kosongkan password saat edit bila tidak ingin mengubah.</div></div>`,`<button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="usu">Simpan</button>`);$("usu").onclick=async()=>{try{await api("saveUser",{item:{userId:u?.userId,username:$("uun").value,name:$("una").value,email:$("uem").value,role:$("urole").value,department:$("udep").value,password:$("upw").value,active:true}});closeModal();toast("User tersimpan","success");users()}catch(e){toast(e.message,"error")}}}

async function receipts(){title("Barang Masuk","Penerimaan stok + scan barcode");await masters();S.receiptItems=[];$("content").innerHTML=`<div class="head"><div><h2>Barang Masuk</h2><p>Scan barcode untuk menambahkan barang.</p></div><button class="btn info" id="rscan">▣ Scan Barcode</button></div><div class="card"><div class="fg3">${select("rsup","Supplier",S.suppliers.map(x=>[x.supplierId,x.name]),"")}${field("rdoc","Nomor Dokumen","")}${field("rdate","Tanggal",today(),"date")}</div><div style="font-weight:800;margin:13px 0 7px">Item</div><div id="rit"></div>${field("rnote","Keterangan")}</div>`;renderReceiptItems();$("rscan").onclick=()=>scannerFor("receive");$("content").querySelector(".card").insertAdjacentHTML("beforeend",'<div style="text-align:right;margin-top:10px"><button class="btn primary" id="rsave">Simpan Barang Masuk</button></div>');$("rsave").onclick=saveReceipt}

function renderReceiptItems(){if(!$('rit'))return;$("rit").innerHTML=S.receiptItems.length?table(["SKU","Barang","Satuan","Stok","Qty","Aksi"],S.receiptItems.map((x,i)=>`<td>${esc(x.sku)}</td><td>${esc(x.name)}</td><td>${esc(x.unit)}</td><td>${nfmt(x.currentStock)}</td><td><input class="inp" data-rqty="${i}" type="number" min="1" value="${x.qty}" style="width:80px"></td><td><button class="btn sm danger" data-rdel="${i}">Hapus</button></td>`)):'<div class="muted" style="padding:18px;text-align:center">Belum ada item. Scan barcode.</div>';document.querySelectorAll('[data-rqty]').forEach(i=>i.oninput=()=>S.receiptItems[Number(i.dataset.rqty)].qty=num(i.value));document.querySelectorAll('[data-rdel]').forEach(b=>b.onclick=()=>{S.receiptItems.splice(Number(b.dataset.rdel),1);renderReceiptItems()})}

async function receiptBarcode(code){const o=await api("searchProducts",{barcode:code}),p=o.items?.[0];if(!p)return toast("Barcode tidak ditemukan","error");const x=S.receiptItems.find(i=>i.productId===p.productId);x?x.qty++:S.receiptItems.push({...p,qty:1});renderReceiptItems();toast(p.name+" ditambahkan","success")}

async function saveReceipt(){if(!S.receiptItems.length)return toast("Item masih kosong","error");try{const o=await api("receiveStock",{supplierId:$("rsup").value,documentNo:$("rdoc").value,receiptDate:$("rdate").value,note:$("rnote").value,items:S.receiptItems.map(x=>({productId:x.productId,qty:num(x.qty)}))});toast("Tersimpan "+o.receiptNo,"success");S.receiptItems=[];renderReceiptItems()}catch(e){toast(e.message,"error")}}

async function adjust(){title("Adjustment / Opname","Sesuaikan stok fisik");await masters();$("content").innerHTML=`<div class="head"><div><h2>Adjustment / Opname</h2></div></div><div class="card"><div class="fg">${select("ap","Barang",S.products.filter(p=>p.active).map(p=>[p.productId,p.name+" ("+p.sku+")"]),"")}${field("aph","Stok Fisik",0,"number")}</div>${field("areason","Alasan") }<div id="ainfo" class="scanbox">Pilih barang.</div><div style="text-align:right;margin-top:10px"><button class="btn primary" id="asave">Simpan</button></div></div>`;$("ap").onchange=()=>{const p=S.products.find(x=>x.productId===$("ap").value);$("ainfo").textContent=p?"Stok sistem: "+nfmt(p.currentStock):"Pilih barang"};$("asave").onclick=async()=>{try{await api("adjustStock",{productId:$("ap").value,physicalStock:num($("aph").value),reason:$("areason").value});toast("Adjustment tersimpan","success");adjust()}catch(e){toast(e.message,"error")}}}

async function movements(){title("Histori Mutasi","Audit trail stok");$("content").innerHTML=`<div class="head"><div><h2>Histori Mutasi</h2></div></div><div class="card"><div class="toolbar">${field("mf","Dari","","date")}${field("mt","Sampai","","date")}${field("ms","SKU / Barang","")}<div class="field"><label>Jenis</label><select id="mtype" class="sel"><option value="">Semua</option><option>IN</option><option>OUT</option><option>ADJUSTMENT</option><option>OPNAME</option></select></div><button class="btn primary" id="mgo">Filter</button><button class="btn" onclick="window.print()">Print</button></div><div id="mv"></div></div>`;const load=async()=>{const o=await api("listMovements",{from:$("mf").value,to:$("mt").value,sku:$("ms").value,type:$("mtype").value});$("mv").innerHTML=table(["Tanggal","SKU","Barang","Jenis","Qty","Sebelum","Sesudah","Referensi","User"],o.items.map(r=>`<td>${esc(r.movementDate)}</td><td>${esc(r.sku)}</td><td>${esc(r.productName)}</td><td>${badge(r.type)}</td><td>${nfmt(r.qty)}</td><td>${nfmt(r.stockBefore)}</td><td>${nfmt(r.stockAfter)}</td><td>${esc(r.referenceId)}</td><td>${esc(r.userName)}</td>`))};$("mgo").onclick=load;await load()}

function reorderTable(a){return a.length?table(["SKU","Barang","Min","Max","Stok","Outstanding","Rekomendasi","Supplier"],a.map(x=>`<td>${esc(x.sku)}</td><td>${esc(x.name)}</td><td>${nfmt(x.minStock)}</td><td>${nfmt(x.maxStock)}</td><td>${nfmt(x.currentStock)}</td><td>${nfmt(x.outstandingOrder)}</td><td><b>${nfmt(x.recommendedQty)}</b></td><td>${esc(supplierName(x.supplierId))}</td>`)):'<div class="muted" style="padding:18px;text-align:center">Tidak ada rekomendasi order.</div>'}

async function reorder(){title("Rekomendasi Order","Min/Max - Outstanding PO");await masters();const o=await api("reorderRecommendations");$("content").innerHTML=`<div class="head"><div><h2>Rekomendasi Order</h2><p>Qty = Max - Stok - Outstanding PO. Qty order dapat diedit saat membuat PO.</p></div></div><div class="card"><div style="text-align:right;margin-bottom:10px"><button class="btn primary" onclick="poForm([])">+ Buat PO Manual</button></div>${reorderTable(o.items)}</div>`}

async function pos(){title("Purchase Order","Order supplier dan penerimaan");const o=await api("listPurchaseOrders");$("content").innerHTML=`<div class="head"><div><h2>Purchase Order</h2></div><button class="btn primary" id="np">+ Buat PO</button></div><div class="card">${table(["No PO","Tanggal","Supplier","Total","Status","Item","Aksi"],o.items.map(p=>`<td>${esc(p.poNo)}</td><td>${esc(p.orderDate)}</td><td>${esc(p.supplierName)}</td><td>${money(p.totalAmount)}</td><td>${badge(p.status)}</td><td>${p.items.length}</td><td>${["DRAFT","ORDERED","PARTIAL"].includes(p.status)?`<button class="btn sm" data-rpo="${p.poId}">Terima</button>`:""}</td>`))}</div>`;$("np").onclick=()=>poForm([]);$("content").querySelectorAll("[data-rpo]").forEach(b=>b.onclick=async()=>{const p=o.items.find(x=>x.poId===b.dataset.rpo);if(p)poReceive(p)})}

async function poForm(pre){await masters();S.poItems=pre.length?pre.map(x=>({...x,qtyOrdered:x.recommendedQty})):[];modal(`<div class="mh"><b>Buat Purchase Order</b><button class="btn sm" onclick="closeModal()">✕</button></div><div class="mb">${select("posup","Supplier",S.suppliers.map(x=>[x.supplierId,x.name]),pre[0]?.supplierId||"")}<div class="toolbar" style="margin-top:10px"><div style="flex:1">${select("posprod","Tambah Barang",S.products.filter(x=>x.active).map(x=>[x.productId,`${x.name} (${x.sku})`]),"")}</div><button class="btn sm" id="poadd">+ Barang</button></div><div id="pot"></div></div>`,`<button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="posave">Simpan Draft PO</button>`);renderPoItems();$("poadd").onclick=()=>{const id=$("posprod").value;if(!id)return toast("Pilih barang terlebih dahulu","error");if(S.poItems.some(x=>x.productId===id))return toast("Barang sudah ada di PO","error");const p=S.products.find(x=>x.productId===id);if(p){S.poItems.push({...p,qtyOrdered:1});renderPoItems();$("posprod").value=""}};$("posave").onclick=async()=>{try{const items=S.poItems.filter(x=>num(x.qtyOrdered)>0);if(!$("posup").value)throw new Error("Supplier wajib dipilih.");if(!items.length)throw new Error("Item PO kosong.");const o=await api("createPurchaseOrder",{supplierId:$("posup").value,items:items.map(x=>({productId:x.productId,qtyOrdered:num(x.qtyOrdered),price:num(x.price)}))});closeModal();toast("PO "+o.poNo+" dibuat","success");pos()}catch(e){toast(e.message,"error")}}}

function renderPoItems(){if(!$('pot'))return;$("pot").innerHTML=table(["Barang","Harga","Qty","Subtotal",""],S.poItems.map((x,i)=>`<td>${esc(x.name)}</td><td>${money(x.price)}</td><td><input class="inp" type="number" min="0" value="${x.qtyOrdered||0}" data-pq="${i}" style="width:75px"></td><td>${money(num(x.qtyOrdered)*num(x.price))}</td><td><button class="btn sm danger" data-pd="${i}">×</button></td>`));document.querySelectorAll('[data-pq]').forEach(i=>i.oninput=()=>{S.poItems[Number(i.dataset.pq)].qtyOrdered=num(i.value);renderPoItems()});document.querySelectorAll('[data-pd]').forEach(b=>b.onclick=()=>{S.poItems.splice(Number(b.dataset.pd),1);renderPoItems()})}

function poReceive(po){const a=po.items.filter(x=>num(x.qtyRemaining)>0);modal(`<div class="mh"><b>Penerimaan ${esc(po.poNo)}</b><button class="btn sm" onclick="closeModal()">✕</button></div><div class="mb"><div id="prtab"></div>${field("prdoc","Nomor Dokumen","")}</div>`,`<button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="prsave">Simpan Penerimaan</button>`);$("prtab").innerHTML=table(["Barang","Ordered","Received","Sisa","Terima"],a.map((x,i)=>`<td>${esc(x.productName)}</td><td>${nfmt(x.qtyOrdered)}</td><td>${nfmt(x.qtyReceived)}</td><td>${nfmt(x.qtyRemaining)}</td><td><input class="inp" type="number" min="0" max="${x.qtyRemaining}" value="0" data-pr="${i}" style="width:75px"></td>`));$("prsave").onclick=async()=>{try{const items=a.map((x,i)=>({poItemId:x.poItemId,qtyReceived:num(document.querySelector(`[data-pr="${i}"]`).value)})).filter(x=>x.qtyReceived>0);if(!items.length)throw new Error("Qty penerimaan kosong.");const o=await api("receivePurchaseOrder",{poId:po.poId,items,documentNo:$("prdoc").value});closeModal();toast("Penerimaan "+o.receiptNo+" tersimpan","success");pos()}catch(e){toast(e.message,"error")}}}

async function requests(){title("Approval Pengajuan","Proses pengajuan Staff");const o=await api("listRequests");$("content").innerHTML=`<div class="head"><div><h2>Approval Pengajuan</h2></div></div><div class="card">${reqTable(o.items,true)}</div>`}

async function myrequests(){title("Pengajuan Saya","Riwayat pengajuan");const o=await api("listRequests");$("content").innerHTML=`<div class="head"><div><h2>Pengajuan Saya</h2></div><button class="btn primary" id="nreq">+ Pengajuan</button></div><div class="card">${reqTable(o.items,false)}</div>`;$("nreq").onclick=()=>requestForm()}

function reqTable(a,admin){return a.length?table(["No","Tanggal","Staff","Status","Detail","Aksi"],a.map(r=>`<td>${esc(r.requestNo)}</td><td>${esc(r.requestDate)}</td><td>${esc(r.staffName)}</td><td>${badge(r.status)}</td><td>${r.items.map(i=>esc(i.productName)+" ("+nfmt(i.qtyRequested)+" → "+nfmt(i.qtyApproved||0)+")").join("<br>")}</td><td>${admin&&r.status==="MENUNGGU"?`<button class="btn sm success" data-process="${r.requestId}">Proses</button>`:""} <button class="btn sm" data-print="${r.requestId}">Print</button>${!admin&&r.status==="MENUNGGU"?` <button class="btn sm danger" data-cancel="${r.requestId}">Batal</button>`:""}</td>`)): '<div class="muted" style="padding:18px;text-align:center">Belum ada pengajuan.</div>'}

async function requestForm(){await masters();S.requestItems=[];modal(`<div class="mh"><b>Pengajuan Barang</b><button class="btn sm" onclick="closeModal()">✕</button></div><div class="mb"><div class="toolbar">${field("rq","Cari Barang","")}<button class="btn info" id="rqscan">▣ Scan</button></div><div id="rres"></div><div style="font-weight:800;margin:12px 0 6px">Item Dipilih</div><div id="rqitems"></div>${field("rqnote","Keterangan","")}</div>`,`<button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="rqsave">Kirim Pengajuan</button>`);$("rq").oninput=()=>{clearTimeout(S.rtimer);S.rtimer=setTimeout(async()=>{const o=await api("searchProducts",{q:$("rq").value});$("rres").innerHTML=o.items?.length?'<div class="list">'+o.items.slice(0,8).map(p=>`<div class="listitem"><div><b>${esc(p.name)}</b><div class="muted" style="font-size:10px">${esc(p.sku)} • Stok ${nfmt(p.currentStock)} ${esc(p.unit)}</div></div><button class="btn sm primary" data-addreq="${p.productId}">Pilih</button></div>`).join("")+ '</div>':'<div class="muted" style="font-size:11px">Tidak ditemukan.</div>';document.querySelectorAll('[data-addreq]').forEach(b=>b.onclick=()=>{const p=S.products.find(x=>x.productId===b.dataset.addreq);if(p){const x=S.requestItems.find(i=>i.productId===p.productId);x?x.qtyRequested++:S.requestItems.push({...p,qtyRequested:1});renderReqItems()}})},250)};$("rqscan").onclick=()=>scannerFor("request");$("rqsave").onclick=async()=>{try{if(!S.requestItems.length)throw new Error("Pilih minimal satu barang.");const o=await api("createRequest",{items:S.requestItems.map(x=>({productId:x.productId,qtyRequested:num(x.qtyRequested),note:$("rqnote").value}))});closeModal();toast("Pengajuan "+o.requestNo+" dikirim","success");myrequests()}catch(e){toast(e.message,"error")}};renderReqItems()}

function renderReqItems(){if(!$('rqitems'))return;$("rqitems").innerHTML=S.requestItems.length?table(["Barang","Stok","Qty",""],S.requestItems.map((x,i)=>`<td>${esc(x.name)}</td><td>${nfmt(x.currentStock)} ${esc(x.unit)}</td><td><input class="inp" type="number" min="1" value="${x.qtyRequested}" data-rqi="${i}" style="width:75px"></td><td><button class="btn sm danger" data-rqd="${i}">×</button></td>`)):'<div class="muted" style="padding:12px">Belum ada barang.</div>';document.querySelectorAll('[data-rqi]').forEach(i=>i.oninput=()=>S.requestItems[Number(i.dataset.rqi)].qtyRequested=num(i.value));document.querySelectorAll('[data-rqd]').forEach(b=>b.onclick=()=>{S.requestItems.splice(Number(b.dataset.rqd),1);renderReqItems()})}

async function processRequest(id){const o=await api("listRequests"),r=o.items.find(x=>x.requestId===id);if(!r)return;modal(`<div class="mh"><b>Proses ${esc(r.requestNo)}</b><button class="btn sm" onclick="closeModal()">✕</button></div><div class="mb"><div class="scanbox">Stok akan dicek ulang saat approval. Qty Disetujui tidak boleh melebihi stok terbaru.</div>${table(["Barang","Diminta","Stok Saat Request","Qty Disetujui"],r.items.map(i=>`<td>${esc(i.productName)}</td><td>${nfmt(i.qtyRequested)}</td><td>${nfmt(i.stockAtRequest)}</td><td><input class="inp" type="number" min="0" value="${Math.min(num(i.qtyRequested),num(i.stockAtRequest))}" data-app="${i.requestItemId}" style="width:85px"></td>`))}${field("rejreason","Alasan Reject (wajib jika Reject)","")}</div>`,`<button class="btn danger" id="reject">Reject</button><button class="btn success" id="approve">Approve</button>`);$("approve").onclick=async()=>{const approvedItems={};document.querySelectorAll('[data-app]').forEach(x=>approvedItems[x.dataset.app]=num(x.value));try{const o=await api("approveRequest",{requestId:id,approvedItems});closeModal();toast(o.status.replaceAll("_"," "),"success");requests()}catch(e){toast(e.message,"error")}};$("reject").onclick=async()=>{if(!$("rejreason").value.trim())return toast("Alasan wajib diisi","error");try{await api("rejectRequest",{requestId:id,reason:$("rejreason").value});closeModal();toast("Pengajuan ditolak","success");requests()}catch(e){toast(e.message,"error")}}}

async function report(){title("Laporan Stok","Print dan Export Excel");await masters();const o=await api("stockReport");$("content").innerHTML=`<div class="head"><div><h2>Laporan Stok</h2><p>Total nilai persediaan: ${money(o.totalValue)}</p></div><div><button class="btn" onclick="window.print()">Print</button> <button class="btn info" id="rex">Export Excel</button></div></div><div class="card"><div class="toolbar">${field("rqsr","Cari"," ")}</div><div id="rtable"></div></div>`;$("rqsr").value="";const draw=()=>{const q=$("rqsr").value.toLowerCase(),a=o.items.filter(x=>[x.sku,x.name,x.supplier].some(v=>String(v).toLowerCase().includes(q)));$("rtable").innerHTML=table(["SKU","Nama","Min","Max","Satuan","Sisa","Selisih","Harga","Sub Total","Supplier"],a.map(x=>`<td>${esc(x.sku)}</td><td>${esc(x.name)}</td><td>${nfmt(x.minStock)}</td><td>${nfmt(x.maxStock)}</td><td>${esc(x.unit)}</td><td>${nfmt(x.currentStock)}</td><td>${nfmt(x.difference)}</td><td>${money(x.price)}</td><td>${money(x.subtotal)}</td><td>${esc(x.supplier)}</td>`))};$("rqsr").oninput=draw;$("rex").onclick=()=>excel(o.items,"Laporan_Stok");draw()}

async function importPage(){title("Import Excel","Master barang");$("content").innerHTML=`<div class="head"><div><h2>Import Excel</h2><p>SKU, Barcode, Nama Barang, Kategori, Satuan, Min, Max, Harga, Supplier, Lokasi</p></div></div><div class="card"><input id="file" class="inp" type="file" accept=".xlsx,.xls,.csv" style="max-width:440px"><div id="ip" style="margin-top:12px"></div><div style="text-align:right;margin-top:10px"><button class="btn primary" id="ix" disabled>Import Data</button></div></div>`;$("file").onchange=readExcel;$("ix").onclick=doImport}

async function readExcel(){const f=$("file").files[0];if(!f)return;if(typeof XLSX==="undefined")return toast("Library Excel belum siap","error");const b=await f.arrayBuffer(),wb=XLSX.read(b,{type:"array"}),ws=wb.Sheets[wb.SheetNames[0]];S.importRows=XLSX.utils.sheet_to_json(ws,{defval:""});const req=["SKU","Barcode","Nama Barang","Kategori","Satuan","Min","Max","Harga","Supplier","Lokasi"],miss=req.filter(k=>!(k in (S.importRows[0]||{})));$("ip").innerHTML=`<b>Preview ${S.importRows.length} baris</b>${miss.length?`<div style="color:#b91c1c">Kolom hilang: ${esc(miss.join(", "))}</div>`:""}<div style="margin-top:8px">${miniExcel(S.importRows.slice(0,10))}</div>`;$("ix").disabled=!!miss.length||!S.importRows.length}

function miniExcel(rows){const k=["SKU","Barcode","Nama Barang","Kategori","Satuan","Min","Max","Harga","Supplier","Lokasi"];return rows.length?table(k,rows.map(r=>k.map(x=>`<td>${esc(r[x])}</td>`).join(""))):'<div class="muted">Tidak ada data.</div>'}

async function doImport(){try{await masters();const cm=Object.fromEntries(S.categories.map(x=>[String(x.categoryName||"").trim().toLowerCase(),x.categoryId])),sm=Object.fromEntries(S.suppliers.map(x=>[String(x.name||"").trim().toLowerCase(),x.supplierId]));const items=S.importRows.map(r=>({sku:String(r.SKU||"").trim().toUpperCase(),barcode:String(r.Barcode||"").trim(),name:String(r["Nama Barang"]||"").trim(),categoryId:cm[String(r.Kategori||"").trim().toLowerCase()]||"",unit:String(r.Satuan||"").trim().toUpperCase(),minStock:num(r.Min),maxStock:num(r.Max),price:num(r.Harga),supplierId:sm[String(r.Supplier||"").trim().toLowerCase()]||"",location:String(r.Lokasi||"").trim()}));const o=await api("bulkUpsertProducts",{items});if(o.errors?.length){const first=o.errors.slice(0,5).map(e=>`Baris ${e.row}: ${e.error}`).join(" | ");toast(`Import selesai dengan ${o.errors.length} error. ${first}`,"error")}else{toast(`Import selesai: ${o.created} dibuat, ${o.updated} di-update`,"success")}importPage()}catch(e){toast(e.message,"error")}}

function excel(rows,name){if(typeof XLSX==="undefined")return toast("Library Excel belum siap","error");const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Data");XLSX.writeFile(wb,name+"_"+today()+".xlsx")}

async function search(){title("Cari Barang","Cari manual atau scan barcode");$("content").innerHTML=`<div class="head"><div><h2>Cari Barang</h2><p>Staff dapat mencari dengan nama/SKU atau scan barcode.</p></div><button class="btn info" id="sc">▣ Scan Barcode</button></div><div class="card"><div class="toolbar">${field("sq","Search","")}</div><div id="sr"></div></div>`;const load=async()=>{const o=await api("searchProducts",{q:$("sq").value});catalog(o.items)};$("sq").oninput=()=>{clearTimeout(S.st);S.st=setTimeout(load,250)};$("sc").onclick=()=>scannerFor("search");await load()}

function catalog(items){$("sr").innerHTML=items.length?'<div class="grid g3">'+items.slice(0,30).map(p=>`<div class="card"><div class="muted" style="font-size:10px">${esc(p.sku)}</div><h3 style="margin:6px 0">${esc(p.name)}</h3><div class="muted" style="font-size:11px">${esc(p.unit)} • Stok ${nfmt(p.currentStock)}</div><div style="margin:8px 0">${badge(p.status)}</div><button class="btn sm primary" data-catreq="${p.productId}">Ajukan</button></div>`).join('')+'</div>':'<div class="muted" style="padding:20px;text-align:center">Barang tidak ditemukan.</div>';document.querySelectorAll('[data-catreq]').forEach(b=>b.onclick=()=>requestFromCatalog(b.dataset.catreq))}

async function requestFromCatalog(productId){try{await requestForm();const o=await api("getProduct",{productId});const p=o.item;if(!p)return;const x=S.requestItems.find(i=>i.productId===p.productId);x?x.qtyRequested++:S.requestItems.push({...p,qtyRequested:1});renderReqItems()}catch(e){closeModal();toast(e.message,"error")}}

function scannerFor(target){modal(`<div class="mh"><b>Scan Barcode</b><button class="btn sm" onclick="closeModal()">✕</button></div><div class="mb"><div id="reader" class="reader"></div><div id="scanmsg" class="scanbox">Arahkan barcode ke kamera.</div></div>`,`<button class="btn" onclick="closeModal()">Tutup</button>`);startScanner(target)}

async function startScanner(target){S.scanTarget=target;if(typeof Html5Qrcode==="undefined")return $("scanmsg").textContent="Scanner belum selesai dimuat. Coba lagi.";S.scanner=new Html5Qrcode("reader");try{await S.scanner.start({facingMode:"environment"},{fps:10,qrbox:{width:260,height:160}},async code=>{await scanned(code,target)},()=>{})}catch(e){$("scanmsg").textContent="Kamera gagal dibuka. Pastikan HTTPS dan izin kamera."}}

async function scanned(code,target){if($("scanmsg"))$("scanmsg").textContent="Barcode: "+code;if(target==="product"){$("pbc").value=code;return closeModal()}if(target==="receive"){await receiptBarcode(code);return closeModal()}const o=await api("searchProducts",{barcode:code}),p=o.items?.[0];if(!p)return toast("Barcode tidak ditemukan","error");if(target==="search"){catalog(o.items);closeModal()}else if(target==="request"){const x=S.requestItems.find(i=>i.productId===p.productId);x?x.qtyRequested++:S.requestItems.push({...p,qtyRequested:1});renderReqItems();closeModal()}}

async function stopScanner(){if(S.scanner){try{await S.scanner.stop()}catch(e){}try{S.scanner.clear()}catch(e){}S.scanner=null}}

async function printRequest(id){try{const o=await api("listRequests"),r=o.items.find(x=>x.requestId===id);if(!r)throw new Error("Pengajuan tidak ditemukan");const w=window.open("","_blank","width=900,height=700");w.document.write(`<html><head><title>${esc(r.requestNo)}</title><style>body{font-family:Arial;padding:28px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #333;padding:7px;font-size:12px}h2{text-align:center}</style></head><body><h2>FORM PENGAJUAN BARANG ATK</h2><p>No: ${esc(r.requestNo)}<br>Tanggal: ${esc(r.requestDate)}<br>Staff: ${esc(r.staffName)}<br>Departemen: ${esc(r.department)}</p><table><tr><th>SKU</th><th>Barang</th><th>Satuan</th><th>Qty Diminta</th><th>Qty Disetujui</th></tr>${r.items.map(i=>`<tr><td>${esc(i.sku)}</td><td>${esc(i.productName)}</td><td>${esc(i.unit)}</td><td>${nfmt(i.qtyRequested)}</td><td>${nfmt(i.qtyApproved||0)}</td></tr>`).join("")}</table><p>Status: ${esc(r.status)}</p><p>Alasan/Keterangan: ${esc(r.rejectionReason||"")}</p><script>window.print()<\/script></body></html>`);w.document.close()}catch(e){toast(e.message,"error")}}

function wire(){$("loginForm").onsubmit=login;$("logoutBtn").onclick=()=>logout(true);$("hamb").onclick=()=>$("side").classList.toggle("open");$("pwBtn").onclick=changePw;document.addEventListener("click",e=>{const ed=e.target.closest("[data-ep]");if(ed){const p=S.products.find(x=>x.productId===ed.dataset.ep);if(p)productForm(p)}const tg=e.target.closest("[data-tp]");if(tg){const p=S.products.find(x=>x.productId===tg.dataset.tp);if(p)api("toggleProduct",{productId:p.productId,active:!p.active}).then(products).catch(x=>toast(x.message,"error"))}const pr=e.target.closest("[data-process]");if(pr)processRequest(pr.dataset.process);const cp=e.target.closest("[data-cancel]");if(cp&&confirm("Batalkan pengajuan?"))api("cancelRequest",{requestId:cp.dataset.cancel}).then(myrequests).catch(x=>toast(x.message,"error"));const pp=e.target.closest("[data-print]");if(pp)printRequest(pp.dataset.print)})}

function changePw(){modal(`<div class="mh"><b>Ganti Password</b><button class="btn sm" onclick="closeModal()">✕</button></div><div class="mb"><div class="fg">${field("oldpw","Password lama","","password")}${field("newpw","Password baru","","password")}</div></div>`,`<button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="cpw">Simpan</button>`);$("cpw").onclick=async()=>{try{await api("changePassword",{oldPassword:$("oldpw").value,newPassword:$("newpw").value});closeModal();toast("Password berhasil diubah","success")}catch(e){toast(e.message,"error")}}}
(async()=>{wire();if(S.token)await start()})();
